package com.sunrisedental;

import com.sunrisedental.model.Patient;
import org.junit.Test;
import static org.junit.Assert.*;

public class PatientModelTest {

    @Test
    public void testPatientCreationAndGetters() {
        Patient patient = new Patient(1, "Nimal Perera", "PAT-0001", "Colombo 03", "0771234567");
        
        assertEquals(1, patient.getId());
        assertEquals("Nimal Perera", patient.getPatientName());
        assertEquals("PAT-0001", patient.getPatientIdCode());
        assertEquals("Colombo 03", patient.getAddress());
        assertEquals("0771234567", patient.getPhoneNumber());
    }

    @Test
    public void testAutoPatientIdFormat() {
        int patientId = 5;
        String autoGeneratedId = String.format("PAT-%04d", patientId);
        
        assertEquals("PAT-0005", autoGeneratedId);
    }

    @Test
    public void testPhoneNumberValidation() {
        String validPhone = "0771234567";
        String invalidPhoneText = "077ABC4567";
        String invalidPhoneShort = "123";

        // Regex checks for standard 10-digit Sri Lankan phone format
        assertTrue(validPhone.matches("^0\\d{9}$"));
        assertFalse(invalidPhoneText.matches("^0\\d{9}$"));
        assertFalse(invalidPhoneShort.matches("^0\\d{9}$"));
    }
}
